### ISSUE TITLE
Make fails with rebar: command not found

### ISSUE THREAD

**Issue by SamuelCox** [huiqing/percept2#16]
Hi, I cloned the repo to a linux environment, callled Make and it fails with make: rebar: command not found. Do you have any idea what the problem may be? I assume it's some configuration thing but I am not sure.

Thanks,
-Sam

**Comment by huiqing** [comment]
Hi Sam,

I think you need to install the ‘rebar’ executable first. https://github.com/rebar/rebar

Regards,
Huiqing

**Comment by SamuelCox** [comment]
Hi, I did have rebar installed, but a newer version. I'll try with the older version and see if that fixes it. Thanks.

**Comment by SamuelCox** [comment]
Yep, that was it. Just me being silly, it doesn't work with rebar3 even if you change the makefile to use rebar3. Thanks!

**Comment by huiqing** [comment]
Ok, thanks. The name is a bit misleading,  rebar3 is not simply a new version of rebar, better to think it as a new application.

Regards,
Huiqing
